---
- name: set namespace
  set_fact:
    _namespace: "{{ namespace_prefix }}"

- name: Create namespace for {{ _namespace }}
  k8s:
    state: present
    definition: "{{ lookup('template', role_path ~ '/templates/namespace.j2' ) | from_yaml }}"

- name: Create quota in namespace {{ _namespace }}
  k8s:
    state: present
    namespace: "{{ _namespace }}"
    definition: "{{ lookup('file', role_path ~ '/files/namespace-quota.yml' ) | from_yaml }}"

- name: Create limits in namespace {{ _namespace }}
  k8s:
    state: present
    namespace: "{{ _namespace }}"
    definition: "{{ lookup('file', role_path ~ '/files/namespace-limits.yml' ) | from_yaml }}"

- name: Create admin rolebinding for user{{ user_num }} in namespace {{ _namespace }}
  k8s:
    state: present
    namespace: "{{ _namespace }}"
    definition: "{{ lookup('template', role_path ~ '/templates/namespace-admin-rolebinding.j2' ) | from_yaml }}"

# - name: Check user{{ user_num }} can login
#   command: "oc login --username=user{{ user_num }} --password={{ _user_login_password }} {{ ocwhoami.stdout }} -n {{ _namespace }} --insecure-skip-tls-verify=true --config={{ tmp_dir }}.kube/{{ _namespace }}-config"

- name: Create OperatorGroup for the operators
  k8s:
    state: present
    definition: "{{ lookup('template', role_path ~ '/templates/olm-operatorgroup/single-namespace.j2' ) | from_yaml }}"

- name: Business Automation for {{ _namespace }}
  include_tasks: workload_per_project_businessautomation.yml