---
become_override: False
ocp_username: system:admin
silent: False

tmp_dir: /tmp/ocp4-workload-pam-frontend-demo

_retry: 180
_delay: 10

_ocp_version: v1.13.4+520769a

_businessautomation_csv_version: businessautomation-operator.1.3.0
_user_login_password: openshift